# Generated by Django 5.0.7 on 2024-07-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(max_length=255)),
                ('party_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('votes', models.IntegerField()),
            ],
        ),
    ]
