# Generated by Django 5.0.7 on 2024-07-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='election_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='vote',
            name='region',
            field=models.CharField(default='Tokyo', max_length=255),
        ),
    ]
