# Generated by Django 5.0.7 on 2024-07-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0003_vote_election_date_vote_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='voter_name',
            new_name='candidate_name',
        ),
    ]
