# Generated by Django 5.0.7 on 2024-07-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0004_rename_voter_name_vote_candidate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('age_group', models.CharField(max_length=20)),
                ('total_population', models.IntegerField()),
                ('total_men', models.IntegerField()),
                ('total_women', models.IntegerField()),
                ('japanese_total', models.IntegerField()),
                ('japanese_men', models.IntegerField()),
                ('japanese_women', models.IntegerField()),
                ('foreign_total', models.IntegerField()),
                ('foreign_men', models.IntegerField()),
                ('foreign_women', models.IntegerField()),
            ],
        ),
    ]
