# Generated by Django 5.0.7 on 2024-07-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0005_populationdistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilityRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('rate', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
