# Generated by Django 5.0.7 on 2024-07-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0006_fertilityrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('income_class', models.CharField(max_length=50)),
                ('household_count', models.IntegerField()),
            ],
        ),
    ]
